[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

board = esp32-c6-devkitc-1

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = zigbee.csv
board_build.filesystem = spiffs

build_flags =
    -DZIGBEE_MODE_ZCZR
    -DCORE_DEBUG_LEVEL=5